config:
  impulse_pulumi:base_snapshot_id: f9aa61e8-183a-4a12-89bd-b7ec38fc96f6
  impulse_pulumi:impulse_instance_label: impulse
  impulse_pulumi:impulse_pg_instance_label: impulse_pg
  impulse_pulumi:impulse_pg_plan: vhp-1c-1gb-amd
  impulse_pulumi:impulse_pg_snapshot_id: 13d6ee3a-6110-4fea-9ed8-a38f5767ae30
  impulse_pulumi:impulse_plan: vhp-1c-1gb-amd
  impulse_pulumi:impulse_snapshot_id: 25ba49cc-9bb0-4ac6-b9e8-743634157338
  impulse_pulumi:managed_pg_instance_label: managed_pg
  impulse_pulumi:managed_pg_plan: vhp-1c-1gb-amd
  impulse_pulumi:managed_snapshot_id: 4e21bfdf-10ad-4249-92b6-5e8705718708
  impulse_pulumi:region: atl
  impulse_pulumi:site_plan: vhp-1c-1gb-amd
  impulse_pulumi:ssh_key_path:
    secure: AAABAL61leKmw7CEH/qx5wdQr+ti0v3YNJEt0Pc7gzBzalJIKCR+lAZXHqdms5UdeFLNAntLg3Jxd3q1D+XziJSM
  impulse_pulumi:stripe_fund_cancel_url: https://site.dev.kdeploy.com/profile
  impulse_pulumi:stripe_fund_price_id:
    secure: AAABAJ+fllpC5nnhNSrRgNzatsnS1m5fgF27AlsFpXRL1jGSQFzTLCWXxiLNoe5vivyTstvWarOaQQ/cy2o=
  impulse_pulumi:stripe_fund_success_url: https://site.dev.kdeploy.com/confirm
  impulse_pulumi:stripe_secret_key:
    secure: AAABAGRWyP85stw8Fq4/czAceoij6NbyNpDtiqpXlUdRwdrihoMUT3NpAqfP4l5qq1GvfmqND7W33zDeMPmI4SuJIvcIzJu2fQMcSrvi+/Dym5il9OaNoRbzO6UcqWDtNLUGHxX4A3MK5NoFWsJ1dSein0oltWnRZpFwYjjh5Z/ZI/bcj7Z2828jJw==
  impulse_pulumi:stripe_webhook_secret:
    secure: AAABAKut77l8rlbmPvTEo+cF0zzlJqXBhcRVtE+Fv9L0i3qddOvxXLhJUG4O2uiyRs3PX3i+pMdid0qNKTAB5uyT9akoH5AOoU6l1qZSOnaCQDzCuEE/gtY3z/3UwbhtqQlVYxRv
  impulse_pulumi:supabase_anon_key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indzd2pnYndhdGxzam9xemp2cWNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODI4ODQzMzgsImV4cCI6MTk5ODQ2MDMzOH0.aC1BmX_5ExiEb3uYq5AOgEgc0e1ZXW8DHbWq249Z4IA
  impulse_pulumi:supabase_url: https://wswjgbwatlsjoqzjvqcg.supabase.co
